---
  - name: Launch instance
    ec2:
        key_name: "{{ keypair }}"
        group: ["{{ vpc_prefix }}_SecGroup"]
        instance_type: "{{ instance_type }}"
        image: "ami-01ed306a12b7d1c96"
        wait: true
        instance_tags:
         Name: "{{ vpc_prefix }}_APP"
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ subnet_data.subnet.id }}"
        volumes:
         - device_name: /dev/sdb
           volume_type: gp2
           volume_size: 8
        assign_public_ip: yes
    register: ec2
  - name: allocate a new elastic IP inside a VPC in us-west-2
    ec2_eip:
      region: "{{ aws_region }}"
      in_vpc: yes
      reuse_existing_ip_allowed: yes
      release_on_disassociation: yes
      device_id: "{{ ec2.instance_ids[0]}}"
    register: eip
