---
- name: Install nginx
  become: yes
  package:
    name: nginx
    state: present
- name: move nginx.conf
  become: yes
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- name: Enable service nginx, and nginx is restarted
  become: yes
  service:
    name: nginx
    enabled: yes
    state: restarted
- name: change firewall setting and open https
  become: yes
  firewalld:
    zone: public
    service: https
    permanent: yes
    state: enabled
- name: change firewall setting and open ssh
  become: yes
  firewalld:
    zone: public
    service: ssh
    permanent: yes
    state: enabled
- name: change firewall setting and open http
  become: yes
  firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled