---
  - include_role:
     name: npm
  - name: restart and enable mongodb service
    become: yes
    systemd:
     name: mongod
     state: restarted
     enabled: yes 
  - name: just force systemd to reread configs
    become: yes
    systemd:
     daemon_reload: yes
  - name: reload service nginx, in all cases
    become: yes
    systemd:
     name: nginx
     state: restarted
     enabled: yes
  - name: reload service todoapp, in all cases
    become: yes
    systemd:
     name: todoapp
     state: started
     enabled: yes
  - name: Recursively change ownership of todoapp directory
    become: yes
    file: 
     path: /home/todoapp
     state: directory 
     recurse: yes 
     owner: todoapp
     group: todoapp
     mode: '0755'