---
- name: Install epel-release
  become: yes
  package:
    name: epel-release
    state: installed
- name: Install nginx
  become: yes
  package:
    name: nginx
    state: present
- name: move nginx.conf
  become: yes
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- name: Enable service nginx, and nginx is restarted
  become: yes
  service:
    name: nginx
    enabled: yes
    state: restarted
